### ISSUE TITLE
Follow Hilla minor versioning

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/quarkus-hilla#285]
To be able to add tests introduced by Hilla minor versions, we should consider pinning the quarkus-hilla versioning to the Hilla minor versions.

This means that the current quarkus-hilla main should use Hilla 2.3-SNAPSHOT, and we should create 2.2 and 2.1 branches pinned to the relative Hilla latest version.
At every Hilla minor release, we should create a branch for the newly released version and bump main to the next Hilla snapshot.

The tasks to perform at every minor release (e.g `A.B.0`) should likely be  

* Create quarkus-hilla `A.B` branch from main and pin Hilla version to `A.B.0`
* Update release.yaml to add branch `A.B` the selectable branch list
* Update dependabot configuration to add `A.B` target branch with the following ignore rules
  ```
    ignore:
      - dependency-name: "dev.hilla:*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "com.vaadin:*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
  ```
* Update update-npm-deps.yaml to add `A.B` branch
* Update validation.yaml to add `A.B` branch on push trigger
* Update main to use Hilla `A.<NEXT>-SNAPSHOT`
* Release quarkus-hilla `A.B.0` from branch `A.B`
* optional: create `target/A.B` label for cherry-picks. It could be done on demand.

Tasks:
* [x] Create Branch 2.0
* [x] Create Branch 2.1
* [x] Create Branch 2.2
* [x] Release quarkus-hilla 2.1.0
* [x] Release quarkus-hilla 2.2.0
* [ ] Update main to 2.3-SNAPSHOT with Hilla 2.3-SNAPSHOT and Vaadin 24.2-SNAPSHOT (#307)

After Hilla 2.3 stable release

* [ ] Create Branch 2.3 and update workflows
* [ ] Release quarkus-hilla 2.3.0
* [ ] Update main to 2.4-SNAPSHOT with Hilla 2.4-SNAPSHOT and Vaadin 24.3-SNAPSHOT

Additional tasks to be performed only once:

* [x] Remove Vaadin BOM and property from root parent pom (#284) (#302)
* [ ] Refactor validation-nightly.yaml to create the matrix based on branch names (main, 2.2, 2.1) instead of Hilla versions. Hilla version should be derived from branch name. (#306
